//! Behavior trait and BehaviorManager.
//!
//! Concrete behaviors are listed once in [`behaviors!`]; that macro builds the
//! id enum, owned variant enum, cycle order, and update/draw dispatch.
//!
//! # Why an enum instead of `dyn Behavior` (C++-style virtual dispatch)?
//!
//! Rust *does* support polymorphic/vtable dispatch via trait objects
//! (`Box<dyn Behavior>` / `&dyn Behavior`). We intentionally avoid that here:
//!
//! - **`draw` is generic** over `D: DrawTarget`, so it is not object-safe —
//!   trait objects require a single concrete method signature, and a type
//!   parameter monomorphizes into many functions.
//! - **`no_std` / no allocator** on device — `Box<dyn Trait>` needs a heap
//!   (or awkward lifetime wiring for `&dyn Trait`).
//!
//! The owned [`BehaviorVariant`] enum plus match (generated by the macro) is
//! static tagged-union dispatch — closer to C++ `std::variant` + `std::visit`
//! than to virtual methods — and keeps each behavior inline with no vtable.

use crate::stickman::geometry::StickmanState;
use embedded_graphics::draw_target::DrawTarget;
use embedded_graphics::pixelcolor::Rgb565;

/// Context passed to behaviors during update.
pub struct UpdateContext<'a> {
    pub delta_ms: u64,
    pub display_width: u32,
    pub display_height: u32,
    pub stickman_state: &'a mut StickmanState,
}

/// Plugin behavior that controls stickman animation.
pub trait Behavior {
    fn id(&self) -> BehaviorId;
    fn update(&mut self, ctx: &mut UpdateContext) -> Option<BehaviorId>;
    fn draw<D>(&self, display: &mut D, state: &StickmanState) -> Result<(), D::Error>
    where
        D: DrawTarget<Color = Rgb565>;
}

/// Declare every behavior in cycle order. Expands to [`BehaviorId`], the owned
/// [`BehaviorVariant`] enum, and shared construct/update/draw dispatch.
macro_rules! behaviors {
    ($(($id:ident, $module:ident, $ty:ident)),+ $(,)?) => {
        /// Identifies each behavior for transitions.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum BehaviorId {
            $($id,)+
        }

        const BEHAVIOR_ORDER: &[BehaviorId] = &[$(BehaviorId::$id,)+];

        enum BehaviorVariant {
            $($id(crate::behavior::$module::$ty),)+
        }

        impl BehaviorVariant {
            fn new(id: BehaviorId) -> Self {
                match id {
                    $(BehaviorId::$id => {
                        Self::$id(crate::behavior::$module::$ty::new())
                    })+
                }
            }

            fn update(&mut self, ctx: &mut UpdateContext) -> Option<BehaviorId> {
                match self {
                    $(Self::$id(b) => b.update(ctx),)+
                }
            }

            fn draw<D>(
                &self,
                display: &mut D,
                state: &StickmanState,
            ) -> Result<(), D::Error>
            where
                D: DrawTarget<Color = Rgb565>,
            {
                match self {
                    $(Self::$id(b) => b.draw(display, state),)+
                }
            }
        }
    };
}

behaviors! {
    (Walking, walking, WalkingBehavior),
    (Idle, idle, IdleBehavior),
    (Jumping, jumping, JumpingBehavior),
    (Crouching, crouching, CrouchingBehavior),
    (Begging, begging, BeggingBehavior),
    (Knockback, knockback, KnockbackBehavior),
    (Tumbling, tumbling, TumblingBehavior),
}

/// Manages current behavior and dispatches update/draw.
pub struct BehaviorManager {
    current: BehaviorVariant,
    index: usize,
}

impl BehaviorManager {
    pub fn new(_initial_state: StickmanState) -> Self {
        Self {
            current: BehaviorVariant::new(BehaviorId::Walking),
            index: 0,
        }
    }

    pub fn cycle_next(&mut self) {
        self.index = (self.index + 1) % BEHAVIOR_ORDER.len();
        self.current = BehaviorVariant::new(BEHAVIOR_ORDER[self.index]);
    }

    pub fn update(&mut self, delta_ms: u64, state: &mut StickmanState) {
        let mut ctx = UpdateContext {
            delta_ms,
            display_width: crate::DISPLAY_WIDTH,
            display_height: crate::DISPLAY_HEIGHT,
            stickman_state: state,
        };
        if let Some(next_id) = self.current.update(&mut ctx) {
            // Keep the cycle index aligned when a behavior self-transitions.
            if let Some(i) = BEHAVIOR_ORDER.iter().position(|&id| id == next_id) {
                self.index = i;
            }
            self.current = BehaviorVariant::new(next_id);
        }
    }

    pub fn draw<D>(&self, display: &mut D, state: &StickmanState) -> Result<(), D::Error>
    where
        D: DrawTarget<Color = Rgb565>,
    {
        self.current.draw(display, state)
    }
}
